//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Previgesst.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClientRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientRES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Previgesst.Ressources.ClientRES", typeof(ClientRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À remplir.
        /// </summary>
        public static string ARemplir {
            get {
                return ResourceManager.GetString("ARemplir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce courriel existe déjà.
        /// </summary>
        public static string CourrielExistant {
            get {
                return ResourceManager.GetString("CourrielExistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce nom d&apos;utilisateur existe déjà.
        /// </summary>
        public static string DejaExistant {
            get {
                return ResourceManager.GetString("DejaExistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dépassement du nombre maximum autorisé.
        /// </summary>
        public static string DépassementMax {
            get {
                return ResourceManager.GetString("DépassementMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition d&apos;un utilisateur.
        /// </summary>
        public static string Edition {
            get {
                return ResourceManager.GetString("Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer.
        /// </summary>
        public static string Effacer {
            get {
                return ResourceManager.GetString("Effacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déjà existant.
        /// </summary>
        public static string IdentificateurDeja {
            get {
                return ResourceManager.GetString("IdentificateurDeja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification début cadenassage.
        /// </summary>
        public static string NotificationDebutCad {
            get {
                return ResourceManager.GetString("NotificationDebutCad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification de non-conformité.
        /// </summary>
        public static string NotificationNonConformite {
            get {
                return ResourceManager.GetString("NotificationNonConformite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On ne peut pas être à la fois Admin et Lecture pour une application.
        /// </summary>
        public static string PasAdminEtLecture {
            get {
                return ResourceManager.GetString("PasAdminEtLecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateurs.
        /// </summary>
        public static string Utilisateurs {
            get {
                return ResourceManager.GetString("Utilisateurs", resourceCulture);
            }
        }
    }
}
