//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Previgesst.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClientLoginRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientLoginRES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Previgesst.Ressources.ClientLoginRES", typeof(ClientLoginRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer le mot de passe.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe oublié?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;enterprise.
        /// </summary>
        public static string IdentificateurCIE {
            get {
                return ResourceManager.GetString("IdentificateurCIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez confirmer votre mot de passe..
        /// </summary>
        public static string MissingConfirmPassword {
            get {
                return ResourceManager.GetString("MissingConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez entrer votre nouveau mot de passe.
        /// </summary>
        public static string MissingNewPassword {
            get {
                return ResourceManager.GetString("MissingNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez entrer votre mot de passe..
        /// </summary>
        public static string MissingPassword {
            get {
                return ResourceManager.GetString("MissingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez entrer votre nom d&apos;utilisateur..
        /// </summary>
        public static string MissingUsername {
            get {
                return ResourceManager.GetString("MissingUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string MotPasse {
            get {
                return ResourceManager.GetString("MotPasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau mot de passe.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro d&apos;utilisateur.
        /// </summary>
        public static string NomUsager {
            get {
                return ResourceManager.GetString("NomUsager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe doit être identique..
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez entrer un mot de passe de {1} caractères ou plus..
        /// </summary>
        public static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se connecter.
        /// </summary>
        public static string SeConnecter {
            get {
                return ResourceManager.GetString("SeConnecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plateforme des administrateurs.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plateforme corporative.
        /// </summary>
        public static string TitreCorporate {
            get {
                return ResourceManager.GetString("TitreCorporate", resourceCulture);
            }
        }
    }
}
