//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Previgesst.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GridRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GridRES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Previgesst.Ressources.GridRES", typeof(GridRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation de la suppression.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation de duplication.
        /// </summary>
        public static string ConfirmationDuplication {
            get {
                return ResourceManager.GetString("ConfirmationDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contient.
        /// </summary>
        public static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous vraiment supprimer l&apos;élément suivant.
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous dupliquer l&apos;élément suivant.
        /// </summary>
        public static string DuplicateMessage {
            get {
                return ResourceManager.GetString("DuplicateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Égal.
        /// </summary>
        public static string Egale {
            get {
                return ResourceManager.GetString("Egale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Étiquette.
        /// </summary>
        public static string Etiquette {
            get {
                return ResourceManager.GetString("Etiquette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non, ne pas dupliquer.
        /// </summary>
        public static string NePasDupliquer {
            get {
                return ResourceManager.GetString("NePasDupliquer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non, ne pas supprimer.
        /// </summary>
        public static string NePasSupprimer {
            get {
                return ResourceManager.GetString("NePasSupprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Différent.
        /// </summary>
        public static string NotEquals {
            get {
                return ResourceManager.GetString("NotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur - Gestions.
        /// </summary>
        public static string NotificationTitle {
            get {
                return ResourceManager.GetString("NotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        public static string Oui {
            get {
                return ResourceManager.GetString("Oui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus grand.
        /// </summary>
        public static string PlusGrand {
            get {
                return ResourceManager.GetString("PlusGrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus grand ou égal.
        /// </summary>
        public static string PlusGrandOuEgal {
            get {
                return ResourceManager.GetString("PlusGrandOuEgal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus petit.
        /// </summary>
        public static string PlusPetit {
            get {
                return ResourceManager.GetString("PlusPetit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus petit ou égal.
        /// </summary>
        public static string PlusPetitOuEgal {
            get {
                return ResourceManager.GetString("PlusPetitOuEgal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require un appareil d&apos;au moins 7.67 pouces.
        /// </summary>
        public static string ScreenRequire {
            get {
                return ResourceManager.GetString("ScreenRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commence par.
        /// </summary>
        public static string StartsWith {
            get {
                return ResourceManager.GetString("StartsWith", resourceCulture);
            }
        }
    }
}
