//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Previgesst.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InstructionRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InstructionRES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Previgesst.Ressources.InstructionRES", typeof(InstructionRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessoire.
        /// </summary>
        public static string Accessoire {
            get {
                return ResourceManager.GetString("Accessoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositif.
        /// </summary>
        public static string Dispositif {
            get {
                return ResourceManager.GetString("Dispositif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition d&apos;une instruction.
        /// </summary>
        public static string EditPopupTitle {
            get {
                return ResourceManager.GetString("EditPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter vers Excel.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificateur.
        /// </summary>
        public static string Identificateur {
            get {
                return ResourceManager.GetString("Identificateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificateur EN.
        /// </summary>
        public static string IdentificateurEN {
            get {
                return ResourceManager.GetString("IdentificateurEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;identificateur ne doit pas dépasser {1} caractères..
        /// </summary>
        public static string IdentificateurMaxLength {
            get {
                return ResourceManager.GetString("IdentificateurMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;identificateur ne doit pas dépasser {1} caractères..
        /// </summary>
        public static string IdentificateurMaxLengthEN {
            get {
                return ResourceManager.GetString("IdentificateurMaxLengthEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des instructions.
        /// </summary>
        public static string InstructionHeading {
            get {
                return ResourceManager.GetString("InstructionHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string LinkInstructions {
            get {
                return ResourceManager.GetString("LinkInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur - Gestions.
        /// </summary>
        public static string NotificationTitle {
            get {
                return ResourceManager.GetString("NotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texte.
        /// </summary>
        public static string Texte {
            get {
                return ResourceManager.GetString("Texte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texte EN.
        /// </summary>
        public static string TexteEn {
            get {
                return ResourceManager.GetString("TexteEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le texte ne doit pas dépasser {1} caractères..
        /// </summary>
        public static string TexteMaxLength {
            get {
                return ResourceManager.GetString("TexteMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le texte ne doit pas dépasser {1} caractères..
        /// </summary>
        public static string TexteMaxLengthEn {
            get {
                return ResourceManager.GetString("TexteMaxLengthEn", resourceCulture);
            }
        }
    }
}
