//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Previgesst.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegistreRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegistreRES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Previgesst.Ressources.RegistreRES", typeof(RegistreRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string Accueil {
            get {
                return ResourceManager.GetString("Accueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interventions en cours.
        /// </summary>
        public static string ActionEnCours {
            get {
                return ResourceManager.GetString("ActionEnCours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon compte.
        /// </summary>
        public static string ActionMonCompte {
            get {
                return ResourceManager.GetString("ActionMonCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        public static string ActionParametres {
            get {
                return ResourceManager.GetString("ActionParametres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procédures.
        /// </summary>
        public static string ActionProcedures {
            get {
                return ResourceManager.GetString("ActionProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programme.
        /// </summary>
        public static string ActionProgramme {
            get {
                return ResourceManager.GetString("ActionProgramme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervention terminés.
        /// </summary>
        public static string ActionTermines {
            get {
                return ResourceManager.GetString("ActionTermines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déconnexion.
        /// </summary>
        public static string SeDeconnecter {
            get {
                return ResourceManager.GetString("SeDeconnecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre de support.
        /// </summary>
        public static string SupportCenter {
            get {
                return ResourceManager.GetString("SupportCenter", resourceCulture);
            }
        }
    }
}
