//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Previgesst.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UtilisateursRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UtilisateursRES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Previgesst.Ressources.UtilisateursRES", typeof(UtilisateursRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accès refusé, vous n&apos;êtes pas autorisé à accéder à cette ressource..
        /// </summary>
        public static string AccessDeniedMessage {
            get {
                return ResourceManager.GetString("AccessDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actif.
        /// </summary>
        public static string Actif {
            get {
                return ResourceManager.GetString("Actif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Analyse de risque.
        /// </summary>
        public static string ADMAnalyse {
            get {
                return ResourceManager.GetString("ADMAnalyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Documents.
        /// </summary>
        public static string ADMDocument {
            get {
                return ResourceManager.GetString("ADMDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Prévicad.
        /// </summary>
        public static string ADMPrevicad {
            get {
                return ResourceManager.GetString("ADMPrevicad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration des utilisateurs.
        /// </summary>
        public static string AdmUtilisateurs {
            get {
                return ResourceManager.GetString("AdmUtilisateurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditeur.
        /// </summary>
        public static string Auditeur {
            get {
                return ResourceManager.GetString("Auditeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le courriel ne doit pas dépasser {1} caractères..
        /// </summary>
        public static string ErreurCourriel {
            get {
                return ResourceManager.GetString("ErreurCourriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe  ne doit pas dépasser {1} caractères..
        /// </summary>
        public static string ErreurMotPasse {
            get {
                return ResourceManager.GetString("ErreurMotPasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom  ne doit pas dépasser {1} caractères..
        /// </summary>
        public static string ErreurNom {
            get {
                return ResourceManager.GetString("ErreurNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom d&apos;usager ne doit pas dépasser {1} caractères.&quot;.
        /// </summary>
        public static string ErreurNomUtilisateur {
            get {
                return ResourceManager.GetString("ErreurNomUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCÈS.
        /// </summary>
        public static string HeadingAcces {
            get {
                return ResourceManager.GetString("HeadingAcces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTIFICATIONS.
        /// </summary>
        public static string HeadingNotifications {
            get {
                return ResourceManager.GetString("HeadingNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARAMÈTRES.
        /// </summary>
        public static string HeadingParameters {
            get {
                return ResourceManager.GetString("HeadingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture Analyse de risque.
        /// </summary>
        public static string LectureAnalyse {
            get {
                return ResourceManager.GetString("LectureAnalyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture Documents.
        /// </summary>
        public static string LectureDocument {
            get {
                return ResourceManager.GetString("LectureDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture Prévicad.
        /// </summary>
        public static string LecturePrevicad {
            get {
                return ResourceManager.GetString("LecturePrevicad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string Modifier {
            get {
                return ResourceManager.GetString("Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string MotDePasse {
            get {
                return ResourceManager.GetString("MotDePasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;usager.
        /// </summary>
        public static string NomUsager {
            get {
                return ResourceManager.GetString("NomUsager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications de début de cadenassage.
        /// </summary>
        public static string NotificationDebutCad {
            get {
                return ResourceManager.GetString("NotificationDebutCad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification de non-conformité.
        /// </summary>
        public static string NotificationNonConformite {
            get {
                return ResourceManager.GetString("NotificationNonConformite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
