//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Previgesst.Ressources.Cadenassage {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CadEditRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CadEditRES() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Previgesst.Ressources.Cadenassage.CadEditRES", typeof(CadEditRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fiche de cadenassage.
        /// </summary>
        public static string Cadenassage {
            get {
                return ResourceManager.GetString("Cadenassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres compte.
        /// </summary>
        public static string CadParamAdmin {
            get {
                return ResourceManager.GetString("CadParamAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Centre de support.
        /// </summary>
        public static string CentreSupport {
            get {
                return ResourceManager.GetString("CentreSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des départements.
        /// </summary>
        public static string Departements {
            get {
                return ResourceManager.GetString("Departements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des accès.
        /// </summary>
        public static string Employes {
            get {
                return ResourceManager.GetString("Employes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarder.
        /// </summary>
        public static string Enregistrer {
            get {
                return ResourceManager.GetString("Enregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des équipements.
        /// </summary>
        public static string Equipements {
            get {
                return ResourceManager.GetString("Equipements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Procédures de contrôle des sources d&apos;énergie.
        /// </summary>
        public static string FichesCadenassage {
            get {
                return ResourceManager.GetString("FichesCadenassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion du cadenassage.
        /// </summary>
        public static string Gestion {
            get {
                return ResourceManager.GetString("Gestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hyperlien utilisateur.
        /// </summary>
        public static string LienUtilisateur {
            get {
                return ResourceManager.GetString("LienUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notifications de début de cadenassage.
        /// </summary>
        public static string NotificationDebutCad {
            get {
                return ResourceManager.GetString("NotificationDebutCad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Programme de cadenassage.
        /// </summary>
        public static string Programme {
            get {
                return ResourceManager.GetString("Programme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Registre des interventions.
        /// </summary>
        public static string Registre {
            get {
                return ResourceManager.GetString("Registre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prévicad - Gestion du cadenassage.
        /// </summary>
        public static string TitreSectionCadenassage {
            get {
                return ResourceManager.GetString("TitreSectionCadenassage", resourceCulture);
            }
        }
    }
}
