//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Previgesst.Ressources.Cadenassage {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CadEditFicheRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CadEditFicheRES() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Previgesst.Ressources.Cadenassage.CadEditFicheRES", typeof(CadEditFicheRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fiches de cadenassage de.
        /// </summary>
        public static string CartesDe {
            get {
                return ResourceManager.GetString("CartesDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Centre de support.
        /// </summary>
        public static string CentreSupport {
            get {
                return ResourceManager.GetString("CentreSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création d&apos;une fiche.
        /// </summary>
        public static string CreationFiche {
            get {
                return ResourceManager.GetString("CreationFiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Édition de la fiche .
        /// </summary>
        public static string EditionFiche {
            get {
                return ResourceManager.GetString("EditionFiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Étapes de cadenassage.
        /// </summary>
        public static string EtapesCadenassage {
            get {
                return ResourceManager.GetString("EtapesCadenassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Étapes de décadenassage.
        /// </summary>
        public static string EtapesDecadenassage {
            get {
                return ResourceManager.GetString("EtapesDecadenassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion du cadenassage.
        /// </summary>
        public static string GestionCadenassage {
            get {
                return ResourceManager.GetString("GestionCadenassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations générales.
        /// </summary>
        public static string InformationsGenerales {
            get {
                return ResourceManager.GetString("InformationsGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Matériel requis.
        /// </summary>
        public static string MaterielRequis {
            get {
                return ResourceManager.GetString("MaterielRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nous joindre.
        /// </summary>
        public static string PeriodeDEssaieBouton {
            get {
                return ResourceManager.GetString("PeriodeDEssaieBouton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez nous contacter pour modifier votre abonnement..
        /// </summary>
        public static string PeriodeDEssaieContact {
            get {
                return ResourceManager.GetString("PeriodeDEssaieContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez atteint le nombre de fiches actives offertes avec votre abonnement..
        /// </summary>
        public static string PeriodeDEssaieTexte {
            get {
                return ResourceManager.GetString("PeriodeDEssaieTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les limites de votre compte sont atteintes.
        /// </summary>
        public static string PeriodeDEssaieTitre {
            get {
                return ResourceManager.GetString("PeriodeDEssaieTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour à la page d’accueil.
        /// </summary>
        public static string Retour {
            get {
                return ResourceManager.GetString("Retour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sources d&apos;énergie.
        /// </summary>
        public static string SourcesEnergie {
            get {
                return ResourceManager.GetString("SourcesEnergie", resourceCulture);
            }
        }
    }
}
