//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Previgesst.Ressources.Cadenassage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CadEquipRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CadEquipRES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Previgesst.Ressources.Cadenassage.CadEquipRES", typeof(CadEquipRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessoires.
        /// </summary>
        public static string Accessoires {
            get {
                return ResourceManager.GetString("Accessoires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string Ajouter {
            get {
                return ResourceManager.GetString("Ajouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer l&apos;image.
        /// </summary>
        public static string ChangerImage {
            get {
                return ResourceManager.GetString("ChangerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Équipements QR Code.
        /// </summary>
        public static string CreateEquipmentQR {
            get {
                return ResourceManager.GetString("CreateEquipmentQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détailles.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositif.
        /// </summary>
        public static string Dispositif {
            get {
                return ResourceManager.GetString("Dispositif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition d&apos;équipements énergétiques.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer.
        /// </summary>
        public static string Effacer {
            get {
                return ResourceManager.GetString("Effacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion d&apos;énergie.
        /// </summary>
        public static string EnergyManagement {
            get {
                return ResourceManager.GetString("EnergyManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des équipements.
        /// </summary>
        public static string EquipmentMgmt {
            get {
                return ResourceManager.GetString("EquipmentMgmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Énergie Gestion des équipements.
        /// </summary>
        public static string EquipmentMgmtEnergy {
            get {
                return ResourceManager.GetString("EquipmentMgmtEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ Accessoires est obligatoire..
        /// </summary>
        public static string ErreurNoAccessories {
            get {
                return ResourceManager.GetString("ErreurNoAccessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ Dépôt est obligatoire..
        /// </summary>
        public static string ErreurNoDeposit {
            get {
                return ResourceManager.GetString("ErreurNoDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ Énergie est obligatoire..
        /// </summary>
        public static string ErreurNoEnergy {
            get {
                return ResourceManager.GetString("ErreurNoEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreurs.
        /// </summary>
        public static string Erreurs {
            get {
                return ResourceManager.GetString("Erreurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur - Gestions.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paysage.
        /// </summary>
        public static string Landscape {
            get {
                return ResourceManager.GetString("Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez sélectionner l&apos;équipement pour imprimer le code QR..
        /// </summary>
        public static string MissingEquipments {
            get {
                return ResourceManager.GetString("MissingEquipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez sélectionner un modèle d&apos;impression..
        /// </summary>
        public static string MissingOptions {
            get {
                return ResourceManager.GetString("MissingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez sélectionner l&apos;orientation de la page.
        /// </summary>
        public static string MissingOrientation {
            get {
                return ResourceManager.GetString("MissingOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle énergie.
        /// </summary>
        public static string NewEnergy {
            get {
                return ResourceManager.GetString("NewEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;équipement.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;équipement (EN).
        /// </summary>
        public static string NomEN {
            get {
                return ResourceManager.GetString("NomEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;équipement (FR).
        /// </summary>
        public static string NomFR {
            get {
                return ResourceManager.GetString("NomFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il n&apos;y a pas de codes QR disponibles..
        /// </summary>
        public static string NoQRAvailable {
            get {
                return ResourceManager.GetString("NoQRAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Équipement.
        /// </summary>
        public static string Num {
            get {
                return ResourceManager.GetString("Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        public static string Portrait {
            get {
                return ResourceManager.GetString("Portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprime moi.
        /// </summary>
        public static string PrintMe {
            get {
                return ResourceManager.GetString("PrintMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimer le code QR.
        /// </summary>
        public static string PrintQRCode {
            get {
                return ResourceManager.GetString("PrintQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. 60503 [3,5 x 5 pouces] 4 par feuille.
        /// </summary>
        public static string QROption1 {
            get {
                return ResourceManager.GetString("QROption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. 60505 [2 x 4 pouces] 10 par feuilles.
        /// </summary>
        public static string QROption2 {
            get {
                return ResourceManager.GetString("QROption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. 5524 [1/3 X 4 pouces]  6 par feuilles.
        /// </summary>
        public static string QROption3 {
            get {
                return ResourceManager.GetString("QROption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez les codes QR à imprimer.
        /// </summary>
        public static string SelectQRToPrint {
            get {
                return ResourceManager.GetString("SelectQRToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source d’énergie.
        /// </summary>
        public static string SourceEnergie {
            get {
                return ResourceManager.GetString("SourceEnergie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string Vide {
            get {
                return ResourceManager.GetString("Vide", resourceCulture);
            }
        }
    }
}
