//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Previgesst.Ressources.Cadenassage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CadEditFicheRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CadEditFicheRES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Previgesst.Ressources.Cadenassage.CadEditFicheRES", typeof(CadEditFicheRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiches de cadenassage de.
        /// </summary>
        public static string CartesDe {
            get {
                return ResourceManager.GetString("CartesDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre de support.
        /// </summary>
        public static string CentreSupport {
            get {
                return ResourceManager.GetString("CentreSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création d&apos;une fiche.
        /// </summary>
        public static string CreationFiche {
            get {
                return ResourceManager.GetString("CreationFiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition de la fiche .
        /// </summary>
        public static string EditionFiche {
            get {
                return ResourceManager.GetString("EditionFiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Étapes de cadenassage.
        /// </summary>
        public static string EtapesCadenassage {
            get {
                return ResourceManager.GetString("EtapesCadenassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Étapes de décadenassage.
        /// </summary>
        public static string EtapesDecadenassage {
            get {
                return ResourceManager.GetString("EtapesDecadenassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion du cadenassage.
        /// </summary>
        public static string GestionCadenassage {
            get {
                return ResourceManager.GetString("GestionCadenassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations générales.
        /// </summary>
        public static string InformationsGenerales {
            get {
                return ResourceManager.GetString("InformationsGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matériel requis.
        /// </summary>
        public static string MaterielRequis {
            get {
                return ResourceManager.GetString("MaterielRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous joindre.
        /// </summary>
        public static string PeriodeDEssaieBouton {
            get {
                return ResourceManager.GetString("PeriodeDEssaieBouton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez nous contacter pour modifier votre abonnement..
        /// </summary>
        public static string PeriodeDEssaieContact {
            get {
                return ResourceManager.GetString("PeriodeDEssaieContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez atteint le nombre de fiches actives offertes avec votre abonnement..
        /// </summary>
        public static string PeriodeDEssaieTexte {
            get {
                return ResourceManager.GetString("PeriodeDEssaieTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les limites de votre compte sont atteintes.
        /// </summary>
        public static string PeriodeDEssaieTitre {
            get {
                return ResourceManager.GetString("PeriodeDEssaieTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour à la page d’accueil.
        /// </summary>
        public static string Retour {
            get {
                return ResourceManager.GetString("Retour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources d&apos;énergie.
        /// </summary>
        public static string SourcesEnergie {
            get {
                return ResourceManager.GetString("SourcesEnergie", resourceCulture);
            }
        }
    }
}
