//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Previgesst.Ressources.Cadenassage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CadEditRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CadEditRES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Previgesst.Ressources.Cadenassage.CadEditRES", typeof(CadEditRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiche de cadenassage.
        /// </summary>
        public static string Cadenassage {
            get {
                return ResourceManager.GetString("Cadenassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres compte.
        /// </summary>
        public static string CadParamAdmin {
            get {
                return ResourceManager.GetString("CadParamAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre de support.
        /// </summary>
        public static string CentreSupport {
            get {
                return ResourceManager.GetString("CentreSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des départements.
        /// </summary>
        public static string Departements {
            get {
                return ResourceManager.GetString("Departements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des accès.
        /// </summary>
        public static string Employes {
            get {
                return ResourceManager.GetString("Employes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        public static string Enregistrer {
            get {
                return ResourceManager.GetString("Enregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des équipements.
        /// </summary>
        public static string Equipements {
            get {
                return ResourceManager.GetString("Equipements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procédures de contrôle.
        /// </summary>
        public static string FichesCadenassage {
            get {
                return ResourceManager.GetString("FichesCadenassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion du cadenassage.
        /// </summary>
        public static string Gestion {
            get {
                return ResourceManager.GetString("Gestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlien utilisateur.
        /// </summary>
        public static string LienUtilisateur {
            get {
                return ResourceManager.GetString("LienUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Départements.
        /// </summary>
        public static string MenuDepartment {
            get {
                return ResourceManager.GetString("MenuDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Équipements.
        /// </summary>
        public static string MenuEquipment {
            get {
                return ResourceManager.GetString("MenuEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications de début de cadenassage.
        /// </summary>
        public static string NotificationDebutCad {
            get {
                return ResourceManager.GetString("NotificationDebutCad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification de non-conformité.
        /// </summary>
        public static string NotificationNonConformite {
            get {
                return ResourceManager.GetString("NotificationNonConformite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programme de cadenassage.
        /// </summary>
        public static string Programme {
            get {
                return ResourceManager.GetString("Programme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registre des interventions.
        /// </summary>
        public static string Registre {
            get {
                return ResourceManager.GetString("Registre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher par # de fiche.
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser.
        /// </summary>
        public static string SearchReset {
            get {
                return ResourceManager.GetString("SearchReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procédures de contrôle des sources d&apos;énergie.
        /// </summary>
        public static string TitreSectionCadenassage {
            get {
                return ResourceManager.GetString("TitreSectionCadenassage", resourceCulture);
            }
        }
    }
}
