//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Previgesst.Ressources.Cadenassage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CadFichesRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CadFichesRES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Previgesst.Ressources.Cadenassage.CadFichesRES", typeof(CadFichesRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vue.
        /// </summary>
        public static string Actif {
            get {
                return ResourceManager.GetString("Actif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travail à effectuer.
        /// </summary>
        public static string AEffectuer {
            get {
                return ResourceManager.GetString("AEffectuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string Ajouter {
            get {
                return ResourceManager.GetString("Ajouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approuvé par.
        /// </summary>
        public static string ApprouvePar {
            get {
                return ResourceManager.GetString("ApprouvePar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention!.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seuls les fichiers Excel, Word et PDF sont acceptés..
        /// </summary>
        public static string AttentionType {
            get {
                return ResourceManager.GetString("AttentionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun document disponible.
        /// </summary>
        public static string AucunDocument {
            get {
                return ResourceManager.GetString("AucunDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Département.
        /// </summary>
        public static string Departement {
            get {
                return ResourceManager.GetString("Departement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copier.
        /// </summary>
        public static string Dupliquer {
            get {
                return ResourceManager.GetString("Dupliquer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éditer.
        /// </summary>
        public static string Editer {
            get {
                return ResourceManager.GetString("Editer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition d&apos;une ligne.
        /// </summary>
        public static string Edition {
            get {
                return ResourceManager.GetString("Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer.
        /// </summary>
        public static string Effacer {
            get {
                return ResourceManager.GetString("Effacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Équipement.
        /// </summary>
        public static string Equipement {
            get {
                return ResourceManager.GetString("Equipement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        public static string Erreur {
            get {
                return ResourceManager.GetString("Erreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FR.
        /// </summary>
        public static string Fiche {
            get {
                return ResourceManager.GetString("Fiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approuvée.
        /// </summary>
        public static string IsApproved {
            get {
                return ResourceManager.GetString("IsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Fiche.
        /// </summary>
        public static string NoFiche {
            get {
                return ResourceManager.GetString("NoFiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Équipement.
        /// </summary>
        public static string Num {
            get {
                return ResourceManager.GetString("Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prévi.
        /// </summary>
        public static string Previ {
            get {
                return ResourceManager.GetString("Previ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prévigesst.
        /// </summary>
        public static string Previgesst {
            get {
                return ResourceManager.GetString("Previgesst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rev. Active.
        /// </summary>
        public static string RevActive {
            get {
                return ResourceManager.GetString("RevActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scannez le QR.
        /// </summary>
        public static string ScanQR {
            get {
                return ResourceManager.GetString("ScanQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        public static string Sheet {
            get {
                return ResourceManager.GetString("Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La taille maximale est de 3 Mo..
        /// </summary>
        public static string TailleMaximale {
            get {
                return ResourceManager.GetString("TailleMaximale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telecharger.
        /// </summary>
        public static string Telecharger {
            get {
                return ResourceManager.GetString("Telecharger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travail.
        /// </summary>
        public static string Travail {
            get {
                return ResourceManager.GetString("Travail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string Vide {
            get {
                return ResourceManager.GetString("Vide", resourceCulture);
            }
        }
    }
}
