//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Previgesst.Ressources.Cadenassage {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CadInfoGeneralesRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CadInfoGeneralesRES() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Previgesst.Ressources.Cadenassage.CadInfoGeneralesRES", typeof(CadInfoGeneralesRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actif.
        /// </summary>
        public static string Actif {
            get {
                return ResourceManager.GetString("Actif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher chez le client.
        /// </summary>
        public static string AfficherClient {
            get {
                return ResourceManager.GetString("AfficherClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Approuvé par.
        /// </summary>
        public static string ApprouvePar {
            get {
                return ResourceManager.GetString("ApprouvePar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de création.
        /// </summary>
        public static string DateCreation {
            get {
                return ResourceManager.GetString("DateCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ Date de création est obligatoire.
        /// </summary>
        public static string DateCreationObligatoire {
            get {
                return ResourceManager.GetString("DateCreationObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de révision.
        /// </summary>
        public static string DateRevision {
            get {
                return ResourceManager.GetString("DateRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Département.
        /// </summary>
        public static string Departement {
            get {
                return ResourceManager.GetString("Departement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer.
        /// </summary>
        public static string Enregistrer {
            get {
                return ResourceManager.GetString("Enregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Équipement.
        /// </summary>
        public static string Equipement {
            get {
                return ResourceManager.GetString("Equipement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ Approuvé par ne doit pas dépasser {1} caractères..
        /// </summary>
        public static string ErreurApprouvePar {
            get {
                return ResourceManager.GetString("ErreurApprouvePar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le numéro de fiche ne doit pas dépasser {1} caractères..
        /// </summary>
        public static string ErreurNoFiche {
            get {
                return ResourceManager.GetString("ErreurNoFiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le travail à effectuer (français) ne doit pas dépasser {1} caractères..
        /// </summary>
        public static string ErreurTravail {
            get {
                return ResourceManager.GetString("ErreurTravail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le travail à effectuer (anglais) ne doit pas dépasser {1} caractères..
        /// </summary>
        public static string ErreurTravailEN {
            get {
                return ResourceManager.GetString("ErreurTravailEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aperçu.
        /// </summary>
        public static string Fiche {
            get {
                return ResourceManager.GetString("Fiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mettre à jour.
        /// </summary>
        public static string MiseAJour {
            get {
                return ResourceManager.GetString("MiseAJour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Fiche.
        /// </summary>
        public static string NoFiche {
            get {
                return ResourceManager.GetString("NoFiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner un département.
        /// </summary>
        public static string SelectionnerDepartement {
            get {
                return ResourceManager.GetString("SelectionnerDepartement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner un équipement.
        /// </summary>
        public static string SelectionnerEquipement {
            get {
                return ResourceManager.GetString("SelectionnerEquipement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner un type de fiche.
        /// </summary>
        public static string SelectionnerTypeFiche {
            get {
                return ResourceManager.GetString("SelectionnerTypeFiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travail à effectuer (français).
        /// </summary>
        public static string TravailAEffectuer {
            get {
                return ResourceManager.GetString("TravailAEffectuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travail à effectuer (anglais).
        /// </summary>
        public static string TravailAEffectuerEN {
            get {
                return ResourceManager.GetString("TravailAEffectuerEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de fiche.
        /// </summary>
        public static string TypeFiche {
            get {
                return ResourceManager.GetString("TypeFiche", resourceCulture);
            }
        }
    }
}
