//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Previgesst.Ressources.Cadenassage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CadLigneCadRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CadLigneCadRES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Previgesst.Ressources.Cadenassage.CadLigneCadRES", typeof(CadLigneCadRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessoire.
        /// </summary>
        public static string Accessoire {
            get {
                return ResourceManager.GetString("Accessoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string Ajouter {
            get {
                return ResourceManager.GetString("Ajouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autres instructions.
        /// </summary>
        public static string AutresInstructions {
            get {
                return ResourceManager.GetString("AutresInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadenasser.
        /// </summary>
        public static string Cadenasser {
            get {
                return ResourceManager.GetString("Cadenasser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer l&apos;image.
        /// </summary>
        public static string ChangerImage {
            get {
                return ResourceManager.GetString("ChangerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositif.
        /// </summary>
        public static string Dispositif {
            get {
                return ResourceManager.GetString("Dispositif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition d&apos;une ligne.
        /// </summary>
        public static string Edition {
            get {
                return ResourceManager.GetString("Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer.
        /// </summary>
        public static string Effacer {
            get {
                return ResourceManager.GetString("Effacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        public static string Erreur {
            get {
                return ResourceManager.GetString("Erreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &apos;Texte supplémentaire Dispositif (français)&apos; par ne doit pas dépasser {1} caractères..
        /// </summary>
        public static string ErrTexteSUPDispositif {
            get {
                return ResourceManager.GetString("ErrTexteSUPDispositif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &apos;Texte supplémentaire Dispositif (anglais)&apos; par ne doit pas dépasser {1} caractères..
        /// </summary>
        public static string ErrTexteSUPDispositifEN {
            get {
                return ResourceManager.GetString("ErrTexteSUPDispositifEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &apos;Texte supplémentaire Instruction (français)&apos; par ne doit pas dépasser {1} caractères..
        /// </summary>
        public static string ErrTexteSUPInstruction {
            get {
                return ResourceManager.GetString("ErrTexteSUPInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &apos;Texte supplémentaire Instruction (anglais)&apos; par ne doit pas dépasser {1} caractères..
        /// </summary>
        public static string ErrTexteSUPInstructionEN {
            get {
                return ResourceManager.GetString("ErrTexteSUPInstructionEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction.
        /// </summary>
        public static string Instruction {
            get {
                return ResourceManager.GetString("Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les commentaires sont manquants..
        /// </summary>
        public static string MissingComments {
            get {
                return ResourceManager.GetString("MissingComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;adresse e-mail est manquante..
        /// </summary>
        public static string MissingEmails {
            get {
                return ResourceManager.GetString("MissingEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Ligne.
        /// </summary>
        public static string NoLigne {
            get {
                return ResourceManager.GetString("NoLigne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réaliser.
        /// </summary>
        public static string Realiser {
            get {
                return ResourceManager.GetString("Realiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renuméroter.
        /// </summary>
        public static string Renumeroter {
            get {
                return ResourceManager.GetString("Renumeroter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner une image.
        /// </summary>
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner une instruction.
        /// </summary>
        public static string SelectInstruction {
            get {
                return ResourceManager.GetString("SelectInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut de l&apos;étape.
        /// </summary>
        public static string StepStatus {
            get {
                return ResourceManager.GetString("StepStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Télécharger.
        /// </summary>
        public static string Telecharger {
            get {
                return ResourceManager.GetString("Telecharger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texte supplémentaire Dispositif (français).
        /// </summary>
        public static string TexteSUPDispositif {
            get {
                return ResourceManager.GetString("TexteSUPDispositif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texte supplémentaire Dispositif (anglais).
        /// </summary>
        public static string TexteSUPDispositifEN {
            get {
                return ResourceManager.GetString("TexteSUPDispositifEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texte supplémentaire Instruction (français).
        /// </summary>
        public static string TexteSUPInstruction {
            get {
                return ResourceManager.GetString("TexteSUPInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texte supplémentaire Instruction (anglais).
        /// </summary>
        public static string TexteSUPInstructionEN {
            get {
                return ResourceManager.GetString("TexteSUPInstructionEN", resourceCulture);
            }
        }
    }
}
