//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Previgesst.Ressources.Cadenassage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CadRegRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CadRegRES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Previgesst.Ressources.Cadenassage.CadRegRES", typeof(CadRegRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        public static string Audit {
            get {
                return ResourceManager.GetString("Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditeur.
        /// </summary>
        public static string Auditeur {
            get {
                return ResourceManager.GetString("Auditeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # BT.
        /// </summary>
        public static string BonDeTravail {
            get {
                return ResourceManager.GetString("BonDeTravail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Début.
        /// </summary>
        public static string Debut {
            get {
                return ResourceManager.GetString("Debut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Département.
        /// </summary>
        public static string Departement {
            get {
                return ResourceManager.GetString("Departement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employé.
        /// </summary>
        public static string Employe {
            get {
                return ResourceManager.GetString("Employe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Équipement.
        /// </summary>
        public static string Equipement {
            get {
                return ResourceManager.GetString("Equipement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string Fiche {
            get {
                return ResourceManager.GetString("Fiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin.
        /// </summary>
        public static string Fin {
            get {
                return ResourceManager.GetString("Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin prévue.
        /// </summary>
        public static string FinPrevueLe {
            get {
                return ResourceManager.GetString("FinPrevueLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Emp..
        /// </summary>
        public static string NoEmploye {
            get {
                return ResourceManager.GetString("NoEmploye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note audit.
        /// </summary>
        public static string NoteAudit {
            get {
                return ResourceManager.GetString("NoteAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminé.
        /// </summary>
        public static string Termine {
            get {
                return ResourceManager.GetString("Termine", resourceCulture);
            }
        }
    }
}
