// <auto-generated />
namespace Previgesst.DataContexts.DbContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Previg_37 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Previg_37));
        
        string IMigrationMetadata.Id
        {
            get { return "201903071539157_Previg_37"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
