//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Previgesst.Ressources.Analyse {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ARCreateRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ARCreateRES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Previgesst.Ressources.Analyse.ARCreateRES", typeof(ARCreateRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actif.
        /// </summary>
        public static string AfficherChezClient {
            get {
                return ResourceManager.GetString("AfficherChezClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre de support.
        /// </summary>
        public static string CentreSupport {
            get {
                return ResourceManager.GetString("CentreSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copier.
        /// </summary>
        public static string Copier {
            get {
                return ResourceManager.GetString("Copier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créateur.
        /// </summary>
        public static string Createur {
            get {
                return ResourceManager.GetString("Createur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création d&apos;une analyse.
        /// </summary>
        public static string Creation {
            get {
                return ResourceManager.GetString("Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer.
        /// </summary>
        public static string Creer {
            get {
                return ResourceManager.GetString("Creer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créé le .
        /// </summary>
        public static string DateCreation {
            get {
                return ResourceManager.GetString("DateCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise à jour le .
        /// </summary>
        public static string DateMAJ {
            get {
                return ResourceManager.GetString("DateMAJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document d&apos;analyse.
        /// </summary>
        public static string DocumentAnalyse {
            get {
                return ResourceManager.GetString("DocumentAnalyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copier.
        /// </summary>
        public static string Dupliquer {
            get {
                return ResourceManager.GetString("Dupliquer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string Editer {
            get {
                return ResourceManager.GetString("Editer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition de l&apos;analyse.
        /// </summary>
        public static string EditionAnalyse {
            get {
                return ResourceManager.GetString("EditionAnalyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition de l&apos;analyse de risques.
        /// </summary>
        public static string EditionAnalyseRisque {
            get {
                return ResourceManager.GetString("EditionAnalyseRisque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer.
        /// </summary>
        public static string Effacer {
            get {
                return ResourceManager.GetString("Effacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        public static string Enregistrer {
            get {
                return ResourceManager.GetString("Enregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Équipement.
        /// </summary>
        public static string Equipement {
            get {
                return ResourceManager.GetString("Equipement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        public static string Erreur {
            get {
                return ResourceManager.GetString("Erreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lignes de l&apos;analyse.
        /// </summary>
        public static string Lignes {
            get {
                return ResourceManager.GetString("Lignes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des analyses de .
        /// </summary>
        public static string ListeDesAnalyses {
            get {
                return ResourceManager.GetString("ListeDesAnalyses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du client.
        /// </summary>
        public static string NomClient {
            get {
                return ResourceManager.GetString("NomClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créateur.
        /// </summary>
        public static string NomValidateur {
            get {
                return ResourceManager.GetString("NomValidateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        public static string Non {
            get {
                return ResourceManager.GetString("Non", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Équipement.
        /// </summary>
        public static string NoReference {
            get {
                return ResourceManager.GetString("NoReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        public static string Oui {
            get {
                return ResourceManager.GetString("Oui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renuméroter.
        /// </summary>
        public static string Renumeroter {
            get {
                return ResourceManager.GetString("Renumeroter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour à la page d’accueil.
        /// </summary>
        public static string Retour {
            get {
                return ResourceManager.GetString("Retour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise à jour par.
        /// </summary>
        public static string UserMAJ {
            get {
                return ResourceManager.GetString("UserMAJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string Vide {
            get {
                return ResourceManager.GetString("Vide", resourceCulture);
            }
        }
    }
}
