//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Previgesst.Ressources.Analyse {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ARLignesRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ARLignesRES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Previgesst.Ressources.Analyse.ARLignesRES", typeof(ARLignesRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse de risque.
        /// </summary>
        public static string Analyse {
            get {
                return ResourceManager.GetString("Analyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commentaires.
        /// </summary>
        public static string Categorie {
            get {
                return ResourceManager.GetString("Categorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie de systèmes de commande installés.
        /// </summary>
        public static string CategorieSystemeCommande {
            get {
                return ResourceManager.GetString("CategorieSystemeCommande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conforme aux normes après l&apos;application des mesures.
        /// </summary>
        public static string Conformite {
            get {
                return ResourceManager.GetString("Conformite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conformité&lt;br&gt;aux normes.
        /// </summary>
        public static string ConformiteListe {
            get {
                return ResourceManager.GetString("ConformiteListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situation dangereuse.
        /// </summary>
        public static string DangerSituation {
            get {
                return ResourceManager.GetString("DangerSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de réalisation.
        /// </summary>
        public static string DateDeRealisation {
            get {
                return ResourceManager.GetString("DateDeRealisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dommage potentiel.
        /// </summary>
        public static string DommagePossible {
            get {
                return ResourceManager.GetString("DommagePossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition d&apos;une ligne.
        /// </summary>
        public static string Edition {
            get {
                return ResourceManager.GetString("Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Équipement.
        /// </summary>
        public static string Equipement {
            get {
                return ResourceManager.GetString("Equipement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;indice de risque  doit être un nombre positif ou 0.
        /// </summary>
        public static string ErrIndiceRisque {
            get {
                return ResourceManager.GetString("ErrIndiceRisque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nombre de personnes exposées doit être un nombre positif ou 0.
        /// </summary>
        public static string ErrNbPersonnes {
            get {
                return ResourceManager.GetString("ErrNbPersonnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to État.
        /// </summary>
        public static string Etat {
            get {
                return ResourceManager.GetString("Etat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to État.
        /// </summary>
        public static string etatAnalyse {
            get {
                return ResourceManager.GetString("etatAnalyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Évaluation du risque sans protection.
        /// </summary>
        public static string EvalSansProtection {
            get {
                return ResourceManager.GetString("EvalSansProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Événement dangereux.
        /// </summary>
        public static string EvenementPotentiel {
            get {
                return ResourceManager.GetString("EvenementPotentiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fréquence d&apos;exposition.
        /// </summary>
        public static string Frequence {
            get {
                return ResourceManager.GetString("Frequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravité.
        /// </summary>
        public static string Gravite {
            get {
                return ResourceManager.GetString("Gravite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indice de risque.
        /// </summary>
        public static string IndiceApres {
            get {
                return ResourceManager.GetString("IndiceApres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indice&lt;br&gt;résiduel.
        /// </summary>
        public static string IndiceApresListe {
            get {
                return ResourceManager.GetString("IndiceApresListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indice de risque.
        /// </summary>
        public static string IndiceAvant {
            get {
                return ResourceManager.GetString("IndiceAvant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indice&lt;br&gt;initial.
        /// </summary>
        public static string IndiceAvantListe {
            get {
                return ResourceManager.GetString("IndiceAvantListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indice de risque.
        /// </summary>
        public static string IndiceRisque {
            get {
                return ResourceManager.GetString("IndiceRisque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;indice de risque doit être un nombre positif ou 0.
        /// </summary>
        public static string IndiceRisqueErreur {
            get {
                return ResourceManager.GetString("IndiceRisqueErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ligne.
        /// </summary>
        public static string Ligne {
            get {
                return ResourceManager.GetString("Ligne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesure de prévention en place.
        /// </summary>
        public static string MesurePrevention {
            get {
                return ResourceManager.GetString("MesurePrevention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesures de réduction du risque.
        /// </summary>
        public static string MesuresReduction {
            get {
                return ResourceManager.GetString("MesuresReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nb. de personnes exposées.
        /// </summary>
        public static string NbPersonnes {
            get {
                return ResourceManager.GetString("NbPersonnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Ref..
        /// </summary>
        public static string NoREF {
            get {
                return ResourceManager.GetString("NoREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opérations Tâches.
        /// </summary>
        public static string OPTask {
            get {
                return ResourceManager.GetString("OPTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phénomène dangereux.
        /// </summary>
        public static string PhenomeneDangereux {
            get {
                return ResourceManager.GetString("PhenomeneDangereux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phénomènes&lt;br&gt;Dangereux.
        /// </summary>
        public static string PhenomeneDescriptionListe {
            get {
                return ResourceManager.GetString("PhenomeneDescriptionListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesures correctives/Plan d’action.
        /// </summary>
        public static string PlanAction {
            get {
                return ResourceManager.GetString("PlanAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possibilité d&apos;évitement.
        /// </summary>
        public static string PossibiliteEvitement {
            get {
                return ResourceManager.GetString("PossibiliteEvitement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probabilité d&apos;occurence.
        /// </summary>
        public static string ProbabiliteOccurence {
            get {
                return ResourceManager.GetString("ProbabiliteOccurence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rang.
        /// </summary>
        public static string Rang {
            get {
                return ResourceManager.GetString("Rang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string RangListe {
            get {
                return ResourceManager.GetString("RangListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Règlement / Norme.
        /// </summary>
        public static string Reglement {
            get {
                return ResourceManager.GetString("Reglement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable.
        /// </summary>
        public static string ResponsableAnalyse {
            get {
                return ResourceManager.GetString("ResponsableAnalyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tâche/Opération.
        /// </summary>
        public static string TacheOP {
            get {
                return ResourceManager.GetString("TacheOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnalyseDeRisque.
        /// </summary>
        public static string TitreFichier {
            get {
                return ResourceManager.GetString("TitreFichier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone dangereuse.
        /// </summary>
        public static string ZoneDangereuse {
            get {
                return ResourceManager.GetString("ZoneDangereuse", resourceCulture);
            }
        }
    }
}
