//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Previgesst.Ressources.Analyse {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ARLignesRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ARLignesRES() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Previgesst.Ressources.Analyse.ARLignesRES", typeof(ARLignesRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analyse de risque.
        /// </summary>
        public static string Analyse {
            get {
                return ResourceManager.GetString("Analyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie de système de commande.
        /// </summary>
        public static string Categorie {
            get {
                return ResourceManager.GetString("Categorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie de systèmes de commande installés.
        /// </summary>
        public static string CategorieSystemeCommande {
            get {
                return ResourceManager.GetString("CategorieSystemeCommande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Conforme aux normes après l&apos;application des mesures.
        /// </summary>
        public static string Conformite {
            get {
                return ResourceManager.GetString("Conformite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Conformité&lt;br&gt;aux normes.
        /// </summary>
        public static string ConformiteListe {
            get {
                return ResourceManager.GetString("ConformiteListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Situation dangereuse.
        /// </summary>
        public static string DangerSituation {
            get {
                return ResourceManager.GetString("DangerSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de réalisation.
        /// </summary>
        public static string DateDeRealisation {
            get {
                return ResourceManager.GetString("DateDeRealisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dommage potentiel.
        /// </summary>
        public static string DommagePossible {
            get {
                return ResourceManager.GetString("DommagePossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Édition d&apos;une ligne.
        /// </summary>
        public static string Edition {
            get {
                return ResourceManager.GetString("Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Équipement.
        /// </summary>
        public static string Equipement {
            get {
                return ResourceManager.GetString("Equipement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;indice de risque  doit être un nombre positif ou 0.
        /// </summary>
        public static string ErrIndiceRisque {
            get {
                return ResourceManager.GetString("ErrIndiceRisque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nombre de personnes exposées doit être un nombre positif ou 0.
        /// </summary>
        public static string ErrNbPersonnes {
            get {
                return ResourceManager.GetString("ErrNbPersonnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à État.
        /// </summary>
        public static string Etat {
            get {
                return ResourceManager.GetString("Etat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à État.
        /// </summary>
        public static string etatAnalyse {
            get {
                return ResourceManager.GetString("etatAnalyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Évaluation du risque sans protection.
        /// </summary>
        public static string EvalSansProtection {
            get {
                return ResourceManager.GetString("EvalSansProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Événement dangereux.
        /// </summary>
        public static string EvenementPotentiel {
            get {
                return ResourceManager.GetString("EvenementPotentiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fréquence d&apos;exposition.
        /// </summary>
        public static string Frequence {
            get {
                return ResourceManager.GetString("Frequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gravité.
        /// </summary>
        public static string Gravite {
            get {
                return ResourceManager.GetString("Gravite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indice de risque.
        /// </summary>
        public static string IndiceApres {
            get {
                return ResourceManager.GetString("IndiceApres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indice&lt;br&gt;résiduel.
        /// </summary>
        public static string IndiceApresListe {
            get {
                return ResourceManager.GetString("IndiceApresListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indice de risque.
        /// </summary>
        public static string IndiceAvant {
            get {
                return ResourceManager.GetString("IndiceAvant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indice&lt;br&gt;initial.
        /// </summary>
        public static string IndiceAvantListe {
            get {
                return ResourceManager.GetString("IndiceAvantListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indice de risque.
        /// </summary>
        public static string IndiceRisque {
            get {
                return ResourceManager.GetString("IndiceRisque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;indice de risque doit être un nombre positif ou 0.
        /// </summary>
        public static string IndiceRisqueErreur {
            get {
                return ResourceManager.GetString("IndiceRisqueErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ligne.
        /// </summary>
        public static string Ligne {
            get {
                return ResourceManager.GetString("Ligne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mesure de prévention en place.
        /// </summary>
        public static string MesurePrevention {
            get {
                return ResourceManager.GetString("MesurePrevention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mesures de réduction du risque.
        /// </summary>
        public static string MesuresReduction {
            get {
                return ResourceManager.GetString("MesuresReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb. de personnes exposées.
        /// </summary>
        public static string NbPersonnes {
            get {
                return ResourceManager.GetString("NbPersonnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #Ref..
        /// </summary>
        public static string NoREF {
            get {
                return ResourceManager.GetString("NoREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opérations Tâches.
        /// </summary>
        public static string OPTask {
            get {
                return ResourceManager.GetString("OPTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phénomène dangereux.
        /// </summary>
        public static string PhenomeneDangereux {
            get {
                return ResourceManager.GetString("PhenomeneDangereux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phénomènes&lt;br&gt;Dangereux.
        /// </summary>
        public static string PhenomeneDescriptionListe {
            get {
                return ResourceManager.GetString("PhenomeneDescriptionListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mesures correctives/Plan d’action.
        /// </summary>
        public static string PlanAction {
            get {
                return ResourceManager.GetString("PlanAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Possibilité d&apos;évitement.
        /// </summary>
        public static string PossibiliteEvitement {
            get {
                return ResourceManager.GetString("PossibiliteEvitement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Probabilité d&apos;occurence.
        /// </summary>
        public static string ProbabiliteOccurence {
            get {
                return ResourceManager.GetString("ProbabiliteOccurence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rang.
        /// </summary>
        public static string Rang {
            get {
                return ResourceManager.GetString("Rang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #.
        /// </summary>
        public static string RangListe {
            get {
                return ResourceManager.GetString("RangListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Règlement / Norme.
        /// </summary>
        public static string Reglement {
            get {
                return ResourceManager.GetString("Reglement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Responsable.
        /// </summary>
        public static string ResponsableAnalyse {
            get {
                return ResourceManager.GetString("ResponsableAnalyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tâche/Opération.
        /// </summary>
        public static string TacheOP {
            get {
                return ResourceManager.GetString("TacheOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AnalyseDeRisque.
        /// </summary>
        public static string TitreFichier {
            get {
                return ResourceManager.GetString("TitreFichier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zone dangereuse.
        /// </summary>
        public static string ZoneDangereuse {
            get {
                return ResourceManager.GetString("ZoneDangereuse", resourceCulture);
            }
        }
    }
}
