//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Previgesst.Ressources.Analyse {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ARRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ARRES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Previgesst.Ressources.Analyse.ARRES", typeof(ARRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actif.
        /// </summary>
        public static string Actif {
            get {
                return ResourceManager.GetString("Actif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse de risque.
        /// </summary>
        public static string Analyse {
            get {
                return ResourceManager.GetString("Analyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string ButtonAjouter {
            get {
                return ResourceManager.GetString("ButtonAjouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer les analyses.
        /// </summary>
        public static string ButtonClient {
            get {
                return ResourceManager.GetString("ButtonClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer.
        /// </summary>
        public static string ButtonCreer {
            get {
                return ResourceManager.GetString("ButtonCreer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails.
        /// </summary>
        public static string ButtonDetails {
            get {
                return ResourceManager.GetString("ButtonDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dommages potentiels.
        /// </summary>
        public static string ButtonDommagesPotentiels {
            get {
                return ResourceManager.GetString("ButtonDommagesPotentiels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Événements dangereux.
        /// </summary>
        public static string ButtonEvenements {
            get {
                return ResourceManager.GetString("ButtonEvenements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesures de prévention.
        /// </summary>
        public static string ButtonMesuresDePrevention {
            get {
                return ResourceManager.GetString("ButtonMesuresDePrevention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phénomènes dangereux.
        /// </summary>
        public static string ButtonPhenomenes {
            get {
                return ResourceManager.GetString("ButtonPhenomenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Règlements / Normes.
        /// </summary>
        public static string ButtonReglements {
            get {
                return ResourceManager.GetString("ButtonReglements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situations dangereuses.
        /// </summary>
        public static string ButtonSituations {
            get {
                return ResourceManager.GetString("ButtonSituations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Administratif - Création d&apos;un client.
        /// </summary>
        public static string CreateAdminTitle {
            get {
                return ResourceManager.GetString("CreateAdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition d&apos;une ligne.
        /// </summary>
        public static string Edition {
            get {
                return ResourceManager.GetString("Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        public static string Erreur {
            get {
                return ResourceManager.GetString("Erreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificateur.
        /// </summary>
        public static string Identificateur {
            get {
                return ResourceManager.GetString("Identificateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charger l&apos;image.
        /// </summary>
        public static string ImgWindowTitle {
            get {
                return ResourceManager.GetString("ImgWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string LinkClients {
            get {
                return ResourceManager.GetString("LinkClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listes.
        /// </summary>
        public static string LinkListes {
            get {
                return ResourceManager.GetString("LinkListes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du client.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition de l&apos;analyse de risque.
        /// </summary>
        public static string PageHeading {
            get {
                return ResourceManager.GetString("PageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des analyses de risque.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
    }
}
