//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Previgesst.Ressources.Previcad {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrevIndexRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrevIndexRES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Previgesst.Ressources.Previcad.PrevIndexRES", typeof(PrevIndexRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accès à PRÉVICAD.
        /// </summary>
        public static string Acces {
            get {
                return ResourceManager.GetString("Acces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadenassage.
        /// </summary>
        public static string Cadenassage {
            get {
                return ResourceManager.GetString("Cadenassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre de support.
        /// </summary>
        public static string CentreSupport {
            get {
                return ResourceManager.GetString("CentreSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadenassage En cours.
        /// </summary>
        public static string EnCours {
            get {
                return ResourceManager.GetString("EnCours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentative de connexion non valide..
        /// </summary>
        public static string ErreurConnection {
            get {
                return ResourceManager.GetString("ErreurConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procédures de contrôle des source d’énergie.
        /// </summary>
        public static string Fiches {
            get {
                return ResourceManager.GetString("Fiches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe oublié?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procédures de contrôle.
        /// </summary>
        public static string MenuFiche {
            get {
                return ResourceManager.GetString("MenuFiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiches De Cadenssage.
        /// </summary>
        public static string MobileGridTile {
            get {
                return ResourceManager.GetString("MobileGridTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas de fiche associée a cet équipement.
        /// </summary>
        public static string MobileNoEquipment {
            get {
                return ResourceManager.GetString("MobileNoEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string MotPasse {
            get {
                return ResourceManager.GetString("MotPasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro d&apos;employé.
        /// </summary>
        public static string NoEmploye {
            get {
                return ResourceManager.GetString("NoEmploye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programme de cadenassage.
        /// </summary>
        public static string Programme {
            get {
                return ResourceManager.GetString("Programme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registre de cadenassage.
        /// </summary>
        public static string Registre {
            get {
                return ResourceManager.GetString("Registre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se connecter.
        /// </summary>
        public static string SeConnecter {
            get {
                return ResourceManager.GetString("SeConnecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadenassage Terminés.
        /// </summary>
        public static string Termines {
            get {
                return ResourceManager.GetString("Termines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plateforme des employés.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
    }
}
