//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Previgesst.Ressources.Previcad {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrevFicheRES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrevFicheRES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Previgesst.Ressources.Previcad.PrevFicheRES", typeof(PrevFicheRES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        public static string Aucun {
            get {
                return ResourceManager.GetString("Aucun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bon de travail.
        /// </summary>
        public static string BonDeTravail {
            get {
                return ResourceManager.GetString("BonDeTravail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #BT.
        /// </summary>
        public static string BonDeTravailAbrege {
            get {
                return ResourceManager.GetString("BonDeTravailAbrege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervention.
        /// </summary>
        public static string Cadenasser {
            get {
                return ResourceManager.GetString("Cadenasser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        public static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer la recherche QR.
        /// </summary>
        public static string ClearQRFilter {
            get {
                return ResourceManager.GetString("ClearQRFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Début.
        /// </summary>
        public static string Debut {
            get {
                return ResourceManager.GetString("Debut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Département.
        /// </summary>
        public static string Departement {
            get {
                return ResourceManager.GetString("Departement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Équipement.
        /// </summary>
        public static string Equipement {
            get {
                return ResourceManager.GetString("Equipement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Étiquette.
        /// </summary>
        public static string Etiquette {
            get {
                return ResourceManager.GetString("Etiquette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter vers Excel.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiche.
        /// </summary>
        public static string Fiche {
            get {
                return ResourceManager.GetString("Fiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin.
        /// </summary>
        public static string Fin {
            get {
                return ResourceManager.GetString("Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin&lt;br&gt;prévue.
        /// </summary>
        public static string FinPrevue {
            get {
                return ResourceManager.GetString("FinPrevue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin prévue.
        /// </summary>
        public static string FinPrevueEmploye {
            get {
                return ResourceManager.GetString("FinPrevueEmploye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J’ai appliqué la procédure de contrôle des sources d’énergies dangereuses et de remise en fonction.
        /// </summary>
        public static string LuEtDecadenasse {
            get {
                return ResourceManager.GetString("LuEtDecadenasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je m’engage à lire et à appliquer la procédure de contrôle des sources d’énergies dangereuses.
        /// </summary>
        public static string LuEtEffectue {
            get {
                return ResourceManager.GetString("LuEtEffectue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matériel.
        /// </summary>
        public static string Materiel {
            get {
                return ResourceManager.GetString("Materiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string Modifier {
            get {
                return ResourceManager.GetString("Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Fiche.
        /// </summary>
        public static string NoFiche {
            get {
                return ResourceManager.GetString("NoFiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        public static string Non {
            get {
                return ResourceManager.GetString("Non", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation sur l’étiquette, le lieu, la procédure..
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Sélectionnez un Statut --.
        /// </summary>
        public static string Option1 {
            get {
                return ResourceManager.GetString("Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complété.
        /// </summary>
        public static string Option2 {
            get {
                return ResourceManager.GetString("Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Conforme.
        /// </summary>
        public static string Option3 {
            get {
                return ResourceManager.GetString("Option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Applicable.
        /// </summary>
        public static string Option4 {
            get {
                return ResourceManager.GetString("Option4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Étape de cadenassage et décadenassage et non-conformité.
        /// </summary>
        public static string OptionWindowTitle {
            get {
                return ResourceManager.GetString("OptionWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        public static string Oui {
            get {
                return ResourceManager.GetString("Oui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout logbook.
        /// </summary>
        public static string Registre {
            get {
                return ResourceManager.GetString("Registre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner le QR.
        /// </summary>
        public static string ScanQR {
            get {
                return ResourceManager.GetString("ScanQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner le QR.
        /// </summary>
        public static string ScanQREquip {
            get {
                return ResourceManager.GetString("ScanQREquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher par # de fiche.
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser.
        /// </summary>
        public static string SearchReset {
            get {
                return ResourceManager.GetString("SearchReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer un e-mail.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Étapes.
        /// </summary>
        public static string Steps {
            get {
                return ResourceManager.GetString("Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISE À L&apos;ARRÊT ET CADENASSAGE.
        /// </summary>
        public static string SwitchOff {
            get {
                return ResourceManager.GetString("SwitchOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DÉCADENASSAGE ET REMISE EN FONCTION.
        /// </summary>
        public static string SwitchOn {
            get {
                return ResourceManager.GetString("SwitchOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telecharger.
        /// </summary>
        public static string Telecharger {
            get {
                return ResourceManager.GetString("Telecharger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travail à effectuer.
        /// </summary>
        public static string Travaux {
            get {
                return ResourceManager.GetString("Travaux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corps de l&apos;e-mail.
        /// </summary>
        public static string WarningBodyLabel {
            get {
                return ResourceManager.GetString("WarningBodyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une ou des erreurs ont été signalées par un utilisateur..
        /// </summary>
        public static string WarningDescr {
            get {
                return ResourceManager.GetString("WarningDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avertissement!.
        /// </summary>
        public static string WarningEmailSubject {
            get {
                return ResourceManager.GetString("WarningEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # de la fiche:.
        /// </summary>
        public static string WarningFileId {
            get {
                return ResourceManager.GetString("WarningFileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ligne(s) d’instruction visée(s):.
        /// </summary>
        public static string WarningTexts {
            get {
                return ResourceManager.GetString("WarningTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Au(x) e-mail(s).
        /// </summary>
        public static string WarningToEmails {
            get {
                return ResourceManager.GetString("WarningToEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur:.
        /// </summary>
        public static string WarningUser {
            get {
                return ResourceManager.GetString("WarningUser", resourceCulture);
            }
        }
    }
}
